[package]
name = "receipt"
version = "0.1.0"
edition = "2021"
authors = ["TIKI Inc <hello@mytiki.com>"]
license = "MIT"

[dependencies]
aws-config = "0.49.0"
aws-sdk-s3 = "0.19.0"
lambda_runtime = "0.6.1"
serde = "1.0.136"
serde_json = "1.0.85"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }