[package]
name = "receipt"
version = "0.1.0"
edition = "2021"
authors = ["TIKI Inc <hello@mytiki.com>"]
license = "MIT"

[dependencies]
aws-config = { version = "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.14.0"
tokio = { version = "1", features = ["full"] }
lambda_runtime = "0.6.1"
serde = "1.0.136"
serde_json = "1.0.85"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }