AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Authorizer GitHub deployment

Parameters:
  Name:
    Description: Name of the IAM Role for the deployment
    Type: String
    Default: deploy-core-aws-authorizer

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Name
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:tiki/core-aws-authorizer:*
  Policy:
    Type: AWS::IAM::RolePolicy
    DependsOn: Role
    Properties:
      RoleName: !Ref Name
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: cloudformation:*
            Resource:
              - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/core-aws-authorizer-*
              - !Sub arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action: cloudformation:ListStacks
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - arn:aws:s3:::mytiki-core-ocean-cf-deploy/*
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:UpdateRole
              - iam:DeleteRole
              - iam:TagRole
              - iam:GetRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:UpdateAssumeRolePolicy
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/core-aws-authorizer-*
